### ISSUE TITLE
More levels of categorization

### ISSUE THREAD

**Issue by unlight** [javierbrea/eslint-plugin-boundaries#75] opened 2020-12-18 20:23 UTC
Currently type detection possible if file will be located in specific folder.
It's kind of old type of separation: type of file in one folder: controllers, models, views, etc.
But, there are projects where grouping is happen by feature: Angular X, NestJS (three layered architecture).

Example 1: https://github.com/nestjs/nest/blob/master/sample/01-cats-app/src/app.module.ts
```ts
import { Module } from '@nestjs/common';
import { CatsModule } from './cats/cats.module';
import { CoreModule } from './core/core.module';

@Module({
  imports: [CoreModule, CatsModule],
})
export class AppModule {}
```
Module can import other modules.

And another issue, example 2: https://github.com/nestjs/nest/blob/2525e9406d8f4a4c16c973320176564b447a860f/sample/01-cats-app/src/cats/cats.module.ts

```ts
import { Module } from '@nestjs/common';
import { CatsController } from './cats.controller';
import { CatsService } from './cats.service';

@Module({
  controllers: [CatsController],
  providers: [CatsService],
})
export class CatsModule {}
```
Module can import other modules and any components of own feature, but can not import components of other modules (we can't import FoodService here)

https://github.com/nestjs/nest/blob/2525e9406d8f4a4c16c973320176564b447a860f/sample/01-cats-app/src/cats/cats.service.ts
`cat.service` can import others services and `cat.repository`, and cannot import other repositories (e.g. `food.repository`)

Looks like, currently it's not possible to configure plugin in such way.
So, besides of type, this requires to detect another attribute of the file - feature (sub module, group).

**Comment by javierbrea** [comment] 2020-12-19 11:09
Hi @unlight, thanks for your feedback!

I can see the problem, let me think about how it should be implemented, because there are even another scenarios to take into account. For example, it is a common practice to have also `subtypes`, as in [an atomic design system](https://bradfrost.com/blog/post/atomic-web-design/) in which you may want to categorize the "components" `type` by "atoms", "molecules", "organisms", etc.

So, some architectures need an upper level of categorization, as you explained, and some others need a lower level of categorization.

Without a deeper analysis, I can see two different approaches:

* Add to the plugin two more levels of categorization: `group`, `type`, `subtype`. I have written a draft about how the plugin configuration could look like, but it seems that it might become too complex, even to explain it, and probably will still not cover all possible scenarios.

* Let the user decide completely its own organization using some kind of `regex` or `glob` pattern for detecting as much levels as he wants for each type.

In the second approach, the settings could be described as in:

```json
{
  "settings": {
    "boundaries/types": [
      {
        "name": "element",
        "glob": "src/(*)/(*).([controller|service|repository])",
        "capture": ["domain", "name", "subtype"]
      },
      {
        "name": "component",
        "glob": "src/design-system/([atom|molecule|organism])/(*)",
        "capture": ["subtype", "name"]
      }
    ]
  }
}
```

Now each type has its own levels, so `allowed-types` rule could be defined as in:

```json
{
  "rules": {
    "boundaries/allowed-types": [2,
      [
        {
          "type": "element",
          "rules": [
            {
              "when": {
                "domain": "*",
                "subtype": "module",
                "name": "*"
              },
              "allow": [
                {
                  "type": "element",
                  "domain": "*",
                  "subtype": "module",
                  "name": "*"
                },
                {
                  "type": "element",
                  "domain": "$self",
                  "subtype": "*",
                  "name": "*"
                }
              ]
            }
          ]
        }
      ]
    ]
  }
}
```

Based on your requirements, and the extra one described by me _(It has not necessarily sense in a real project to mix all of them, this is made only for explanation purposes)_, I am going to add an example of a portion of the configuration to see how each correspondent rule could look like:

* Any `element` of `subtype` "module" in any `domain` can import another `element` of `subtype` "module" from any other `domain`
* Any `element` of `subtype` "module" can import any other `subtype` of `element` inside the same `domain` _(Note the usage of the special value `$self`)_

```json
{
  "type": "element",
  "rules": [
    {
      "when": {
        "domain": "*",
        "subtype": "module",
        "name": "*"
      },
      "allow": [
        {
          "type": "element",
          "domain": "*",
          "subtype": "module",
          "name": "*"
        },
        {
          "type": "element",
          "domain": "$self",
          "subtype": "*",
          "name": "*"
        }
      ]
    }
  ]
}
```

* Any `element` of `subtype` "service" in any `domain` can import another `element` of `subtype` "service" from any other `domain`
* Any `element` of `subtype` "service" in any `domain` can import another `element` of `subtype` "repository" inside the same `domain`.

```json
{
  "when": {
    "domain": "*",
    "subtype": "service",
    "name": "*"
  },
  "allow": [
    {
      "type": "element",
      "domain": "*",
      "subtype": "service",
      "name": "*"
    },
    {
      "type": "element",
      "domain": "$self",
      "subtype": "repository",
      "name": "*"
    }
  ]
}
```


* Any `element` of any `subtype` can import any `component` of any `subtype`

```json
{
  "when": {
    "domain": "*",
    "subtype": "*",
    "name": "*"
  },
  "allow": [
    {
      "type": "component",
      "subtype": "*",
      "name": "*"
    }
  ]
}
```
* Any `component` of `subtype` "atom" can import any other `component` of `subtype` "atom"
* Any `component` of `subtype` "molecule" can import any other `component` of `subtype` "atom" or "molecule"
* Any `component` of `subtype` "organism" can import any other `component` of any other `subtype`

```json
{
  "type": "component",
  "rules": [
    {
      "when": {
        "subtype": "atom",
        "name": "*"
      },
      "allow": [
        {
          "type": "component",
          "subtype": "atom",
        }
      ]
    },
    {
      "when": {
        "subtype": "molecule",
        "name": "*"
      },
      "allow": [
        {
          "type": "component",
          "subtype": ["atom", "molecule"]
        }
      ]
    },
    {
      "when": {
        "subtype": "organism",
        "name": "*"
      },
      "allow": [
        {
          "type": "component",
          "subtype": "*"
        }
      ]
    }
  ]
}

```

Take into account that this is only a draft, and there are still many details to take into account and analyze, for example:

* The configuration could seem too much complex and long, but this may be balanced distributing some predefined configurations for the most usual scenarios and frameworks.
* In order to make rules configuration shorter, there are some properties that could have default values, as "*" for every capture, etc. .
* Some kind of backward compatibility or configuration migration script should be also provided to avoid such a big breaking change.

Please, let me know your opinion.

**Comment by javierbrea** [comment] 2020-12-19 17:47
@lichblitz @emmanuelgratuze, the suggested change could allow us to add a `subtype` level of categorization to our components, and a `domain` level to our modules, so I would like to know your opinion too! 🙂

It could even make possible to define the direction of dependencies between domains based on its name, and between components based on its subtype, for example:

```json
{
  "settings": {
    "boundaries/types": [
      {
        "name": "module",
        "glob": "modules/(*)/(*)",
        "capture": ["domain", "name"]
      },
      {
        "name": "component",
        "glob": "components/([atom|molecule|organism])/(*)",
        "capture": ["subtype", "name"]
      }
    ]
  },
 "rules": {
    "boundaries/allowed-types": [2,
      [
        {
          "type": "module",
          "rules": [
            {
              "allow": [
                {
                  "type": "component"
                }
              ]
            },
            {
              "when": {
                "domain": "customers"
              },
              "allow": [
                {
                  "type": "module",
                  "domain": ["billing", "sales"]
                }
              ]
            },
           {
              "when": {
                "domain": "billing"
              },
              "allow": [
                {
                  "type": "module",
                  "domain": "sales"
                }
              ]
            }
          ]
        },
        {
          "type": "component",
          "rules": [
            {
              "when": {
                "subtype": "organism"
              },
              "allow": [
                {
                  "type": "component",
                  "subtype": "molecule"
                }
              ]
            },
            {
              "when": {
                "subtype": "molecule"
              },
              "allow": [
                {
                  "type": "component",
                  "subtype": "atom"
                }
              ]
            }
          ]
        }
      ]
    ]
  }
}
```

**Comment by unlight** [comment] 2020-12-19 18:40
> Please, let me know your opinion.

I see that you already thought about it.
I think the second option that you explain could fulfil our needs. But, as you said, configuration looks complex. Anyway, looks promising. Thank you.

**Comment by javierbrea** [comment] 2021-01-10 10:40
Hi again, I think I have a simpler but still powerful enough solution.

In `settings`, `types` could be defined as simple strings, as currently, or as an object containing `name` and a `glob` pattern. It would be also possible to define `capture`, as in the previous examples, but maintaining the standard `glob` expressions (it would be used the [micromatch `capture` method](https://github.com/micromatch/micromatch#capture)) to capture all matches in pattern, and users could give a name to each capture in the same order that they will be received:

```json
{
  "settings": {
    "boundaries/types": [
      {
        "name": "helpers",
        "pattern": "**/helpers/*"
      },
      {
        "name": "components",
        "pattern": "**/components/*/*",
        "capture": ["parents", "family", "elementName"]
      },
      "views",
      "layouts",
      "pages",
      "app"
    ],
  }
}
```

Doing it this way, settings would be backward compatible, and could be still defined as strings for simple scenarios, or as objects for more complex ones. The pattern for strings would be assigned internally to `**/[string]/*`, so it would match any folder named as the string value, as the plugin currently does.

The other part is how to define allowed types. In this case, it is required a change in the configuration, which currently receives an object. It should receive an array of objects with the keys `from` and `allows`, but maintaining the same simplicity that current settings, so users could define from which elements can be imported other elements using an array of strings in the `allow` property:

```json
{
  "rules": {
    "boundaries/allowed-types": [2,
      [
        {
          "from": "helpers",
          "allow": ["helpers"]
        },
        {
          "from": "components",
          "allow": ["helpers"]
        }
      ]
    ]
  }
}

```

Then, for more complex scenarios, the plugin would give the possibility to use an array with options instead of a string when defining `from`, and `allow` types. The array would have the element type in the first position, and an object with options to use `captures` in the second one, so it could be specified the `capture` values that should have to be applied for that rule, both in `from` or `target` types.

```json
{
  "rules": {
    "boundaries/allowed-types": [2,
      [
        {
          "from": ["helpers", "components"],
          "allow": ["helpers"]
        },
        {
          "from": [["components", { "family": "atom" }]],
          "allow": [
            "helpers",
            ["components", { "family": "atom" }]
          ]
        },
        {
          "from": [["components", { "family": "molecule" }]],
          "allow": [
            "helpers",
            ["components", { "family": "atom" }],
            ["components", { "family": "molecule" }]
          ]
        }
      ]
    ]
  }
}

```

I still have to write an example of the configurations for the @unlight's requirements using this pattern, but I think it could be done easier and simpler than in the previous proposal, and in my opinion the resultant configuration would be more readable.

**Comment by javierbrea** [comment] 2021-01-26 19:42
Hi! I'm glad to announce that I have just published a pre-release of version 2.0.0 (2.0.0-beta.3) which includes changes from this proposal and a lot of new features too. It is already available at NPM: https://www.npmjs.com/package/eslint-plugin-boundaries/v/2.0.0-beta.3.

I want to make some extra tests in real projects before publishing the release, but I hope to make it soon, probably about this weekend. Meanwhile, I would really appreciate feedback about the new documentation, configuration, rules names, etc. Any feedback would be great! 😃   (@emmanuelgratuze, this message is also for you 😉 )

The code is at your disposal in the [pre-release branch](https://github.com/javierbrea/eslint-plugin-boundaries/tree/pre-release) before opening the release PR. 

I have also added a [migration guide](https://github.com/javierbrea/eslint-plugin-boundaries/blob/pre-release/docs/guides/how-to-migrate-from-v1-to-v2.md) that can be useful as a summary to see the differences between v1.x and v2.x.

@unlight, about your requirements, I have added unit tests using the [Cats application from NestJS examples](https://github.com/nestjs/nest/tree/master/sample/01-cats-app) and it is working fine. I will add another comment with the configuration used in the tests, as an example of how it finally would look.

**Comment by javierbrea** [comment] 2021-01-26 19:49
@unlight , here is the configuration that is being used to run unit tests using your requirements. I'm sure that it could be improved and made shorter, but I don't know NestJS enough, so I had to make some assumptions that probably are wrong.

If is it hard to understand without enough context, you can take a look at the [new settings docs here](https://github.com/javierbrea/eslint-plugin-boundaries/tree/pre-release#global-settings), and the [new options of the `element-types` rule here](https://github.com/javierbrea/eslint-plugin-boundaries/blob/pre-release/docs/rules/element-types.md).

```js
{
  settings: {
    "boundaries/elements": [
      {
        type: "main",
        mode: "file",
        pattern: "*/main.js",
      },
      {
        type: "app",
        mode: "file",
        pattern: "*/app.module.js",
      },
      {
        type: "module",
        pattern: "**/*/*.module.js",
        mode: "file",
        capture: ["base", "feature", "fileName"],
      },
      {
        type: "controller",
        pattern: "**/*/*.controller.js",
        mode: "file",
        capture: ["base", "feature", "fileName"],
      },
      {
        type: "service",
        pattern: "**/*/*.service.js",
        mode: "file",
        capture: ["base", "feature", "fileName"],
      },
      {
        type: "interceptor",
        pattern: "**/*/interceptors/*.interceptor.js",
        mode: "file",
        capture: ["base", "feature", "fileName"],
      },
      {
        type: "interface",
        pattern: "**/*/interfaces/*.interface.js",
        mode: "file",
        capture: ["base", "feature", "fileName"],
      },
      {
        type: "dto",
        pattern: "**/*/dto/*.dto.js",
        mode: "file",
        capture: ["base", "feature", "fileName"],
      },
      {
        type: "common",
        pattern: "**/common/*/*.*.js",
        mode: "file",
        capture: ["base", "category", "fileName"],
      },
    ],
  },
  rules: {
    "boundaries/element-types": [
      2,
      {
        default: "disallow",
        rules: [
          {
            from: "app",
            allow: "module",
          },
          {
            from: "module",
            allow: [
              "module",
              ["controller", { feature: "${feature}" }],
              ["service", { feature: "${feature}" }],
              ["interceptor", { feature: "${feature}" }],
            ],
          },
          {
            from: "controller",
            allow: [
              "common",
              ["service", { feature: "${feature}" }],
              ["interface", { feature: "${feature}" }],
              ["dto", { feature: "${feature}" }],
            ],
          },
          {
            from: "service",
            allow: [["interface", { feature: "${feature}" }]],
          },
        ],
      },
    ],
  },
}
```

**Comment by javierbrea** [comment] 2021-01-27 16:56
> Awesome work. I'll try to add plugin/configuration to my test application at this or next weekend.

Ok, thanks for testing it. Don't dude to ask for support if needed.

**Comment by unlight** [comment] 2021-01-28 21:23
I have something to say already.

When I started configuring I got multiples errors "Expected input to be a string" from micromatch, because of invalid configuration.
It would be nice configuration will be guarded by validation, or at least assert to prevent sending non-string values to micromatch.
When seeing this error it's not clear what is wrong.

Multiple match issue.
I saw that `pattern` accept string or array, how it works if value is array?

I must recognize element type, let's name it `model`. And some feature have special model folder (articles), but some
features have really few files (there is no need to create folders with single file)

I can't create configuration to recognize model in both feature folders with and without models folder.

Example structure:
```
src\tag\tag.model.ts
src\aricles\models\article.model.ts
```

settings boundaries/elements
```js
// Does not work
{
    type: 'model',
    pattern: [
        '**/*/*.model.ts',
        '**/*/models/*.{model,dto}.ts',
    ],
    mode: 'file',
    capture: ['base', 'feature', 'elementName'],
}
// Also does not work
{
    type: 'model',
    pattern: '**/*/models/*.{model,dto}.ts',
    mode: 'file',
    capture: ['base', 'feature', 'elementName'],
},
{
    type: 'model',
    pattern: '**/*/*.model.ts',
    mode: 'file',
    capture: ['base', 'feature', 'elementName'],
}
```

Last configuration will not report unknown element, but obviously will be wrongly captured
(`feature = models` for src\aricles\models\article.model.ts)

**Comment by javierbrea** [comment] 2021-01-29 06:56
Hi again!

I am going to separate answers by topic:

## __Validation__
The configuration is being validated with a JSON schema using eslint built-in validation, so the error wouldn't be directly related to it. I would like to know how do you get the error in order to add some extra internal checks. The plugin should ensure that no `null` values are passed to micromatch. Anyway I will try to reproduce it locally in order to fix it. Thank you for noticing it.

## __Pattern as string or array__
The `element-types` and other main rules [use in options what I named `elements matcher`](https://github.com/javierbrea/eslint-plugin-boundaries/blob/pre-release/docs/rules/element-types.md) _(maybe the name is not as clear as I'd like, suggestions with alternatives are welcome)_. So, rule configuration could be expressed as:

#### Elements matchers
```
{
  from: [<elementMatcher>, <elementMatcher>],
  allow: [<elementMatcher>, <elementMatcher>]
}
```
Then, an `<elementMatcher>` can be a `micromatch` pattern as `string` (`"micromatchPattern`), or, as you mentioned, an `array` with a `micromatch` pattern in the first position, and captured values patterns as an `object` in the second position (`["micromatchPattern", { captureKey: "micromatchPattern" }]`). When the `array` format is used, the `elementMatcher` will only match elements with type matching the `string` in the first position, and captured values matching all of the patterns in the `object` provided in the second position. So, __you could say to the plugin "from modules of feature x, allow models of feature y", or "from modules with name x, disallow helpers of type y", or "from modules with type x and name y, allow helpers of name z", etc.__

##### matchers as strings:

```jsonc
{
  from: ["components", "mod*"],
  allow: ["modules", "!helpers"]
}
```

#### matchers as arrays with captured values patterns:

```jsonc
{
  from: [["components", { feature: "foo" }], ["modules", { elementName: "foo-name" }]],
  allow: [["modules", { feature: "x-feature" }], ["!helpers", { feature: "foo" } ]]
}
```

You can read more about this in the [rule docs](https://github.com/javierbrea/eslint-plugin-boundaries/blob/pre-release/docs/rules/element-types.md), and in the [rules configuration section in the main README](https://github.com/javierbrea/eslint-plugin-boundaries/tree/pre-release#rules-configuration). It would be great also to receive some feedback about the documentation, if it's clear enough or not, etc. 🙂

## __How to configure your example__

The first one is not working because the first pattern in the array is probably matching both cases (`src\tag\tag.model.ts`and  `src\aricles\models\article.model.ts`), try inverting the order in the array, because the second pattern is more restrictive and it should be executed at first place.

About the second one, I'm going to test it, but I think it should be working too because in this case the different patterns are declared in the right order. In the first object, it will not give `models` value to `feature`, as `models` is a fixed folder, and `micromatch` won't give it a value when capturing (it only returns captures in the array for expressions like `*`, `**`, etc. Also, returning the same type in different objects is allowed, as the plugin will stop looking for matches on the first one match.

Thank you again for your help! I will add another comment when I have tested your second approach.

**Comment by unlight** [comment] 2021-01-29 19:42
@javierbrea 
By "string or array for pattern" I meant pattern for **boundaries/element-types settings** not rules.

![image](https://user-images.githubusercontent.com/301732/106319470-ec09b480-628a-11eb-871a-ec51db594514.png)

After closer look, now I see that array is not valid value there, I got warning and error
```
[boundaries]: Please provide pattern in 'boundaries/elements' setting

TypeError: Expected a non-empty string // from picomatch
```

**Comment by javierbrea** [comment] 2021-01-29 20:12
@unlight Ok, I didn't understand.

You're right, my fault. It does not support multiple patterns in the `pattern` property of `boundaries/elements` setting. But I think it should, because it could be a good solution for some cases, as in your example. Tomorrow I will publish v2.0.0-beta.4 adding the feature. I will also add unit tests based on your second example, in order to know what can be happening.

**Comment by javierbrea** [comment] 2021-01-30 11:21
I have just published the [release 2.0.0-beta.4](https://github.com/javierbrea/eslint-plugin-boundaries/releases), which supports patterns as arrays, and I have found the causes of the other issues:

#### Validation

The validation problem was related to the support of arrays in the `pattern` property, so it is already fixed.

#### How to configure the examples

The first one example obviously was not working because arrays were not supported. But even now it wouldn't work, because the less restrictive pattern would return a positive match, no matter its position in the array. Let's me explain it more deeply:

As the plugin searches for matches from the right side of the path, when it is trying to find matches for `models\article.model.ts`, the pattern `**/*/models/*.{model,dto}.ts` will not match, but the `**/*/*.model.ts` will do, because `**/` means "any folders, including zero" in micromatch. So it will assign `model` type, which is right, but the captured `feature` will have value `models`, which is wrong.

This can be fixed with different approaches:

* Changing the pattern `**/*/*.model.ts` to `*/*/*.model.ts`, because `models\article.model.ts` won't match with any of the patterns, and `articles\models\article.model.ts` will match with both, so `**/*/models/*.{model,dto}.ts` will be the matching one, as it is executed in first place. Note that the `base` capture won't give you the full base path value in the case of the second pattern, but I suppose that this wouldn't be an inconvenience.

```jsonc
// Works
{
    type: 'model',
    pattern: [
      '**/*/models/*.{model,dto}.ts',
      '*/*/*.model.ts'  
    ],
    mode: 'file',
    capture: ['base', 'feature', 'elementName'],
}
```

* I have added a new choice to the `mode` option called `full`. When setting mode to `full`, the pattern will be applied to the full path, not from the right to the left as it is done in `file` and `folder` modes. In the next example, the first pattern will match before the second one, because it always tries to match with `src\aricles\models\article.model.ts`, not with `models\article.model.ts`, then `aricles\models\article.model.ts`, etc.

```jsonc
// Works
[
{
  type: "model",
  pattern: "**/*/models/*.{model,dto}.js",
  mode: "full",
  capture: ["base", "feature", "fileName"],
},
{
  type: "model",
  pattern: "**/*/*.model.js",
  mode: "file",
  capture: ["base", "feature", "fileName"],
}
]
```

#### Debug mode

In order to help during the configuration process, the plugin can trace information about the files and imports being analyzed. The information includes the file path, the assigned element type, the captured values, etc. So, it can help you to check that your `elements` setting works as expected. You can enable it using the `ESLINT_PLUGIN_BOUNDARIES_DEBUG` environment variable.

```
ESLINT_PLUGIN_BOUNDARIES_DEBUG=1 npm run lint
```

**Comment by unlight** [comment] 2021-01-30 17:16
Thanks.

What I else noticed, lack of context in error messages.

```
path\src\article\article.module.ts 9:29 warning Usage of 'service' is not allowed in 'module' boundaries/element-types
```
What module can be guessed from reported filename (article), but it's not clear what service until I check line 9 of the file.
I would like to see the names here, for example: `Usage of User service is not allowed in Article module`

Maybe add setting which will resolve 'type' to more descriptive name, e.g. setting `{feature} {type}` (default `{type}`) resolves to 'user service' and 'article module'

**Comment by javierbrea** [comment] 2021-02-01 06:30
> What I else noticed, lack of context in error messages.
> [...]
> Maybe add setting which will resolve 'type' to more descriptive name, e.g. setting {feature} {type} (default {type}) resolves to 'user service' and 'article module'

Thanks, good idea! Maybe this option should be supported also in rules options, because depending of the usage of captured values the message should be different for each case. I will open a new issue for this topic.

Any other feedback about main configuration and/or rules options? I think I'm going to publish the 2.0.0 release during this week, as it seems stable enough.

**Comment by unlight** [comment] 2021-02-01 15:48
> Any other feedback about main configuration and/or rules options?

Right now - no.

**Closed** 2021-02-02 06:25 UTC
Labels: enhancement
